"""Add is_urgent to ambulatory records

Revision ID: 4d6e543ef206
Revises: e30793237851
Create Date: 2026-05-30 12:55:19.557206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6e543ef206'
down_revision = 'e30793237851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambulatory_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_urgent', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambulatory_records', schema=None) as batch_op:
        batch_op.drop_column('is_urgent')
    # ### end Alembic commands ###
