"""add_admitted_children_rural

Revision ID: 8e7992f1ab9a
Revises: 20260521_v3_add_bed_profile_name
Create Date: 2026-05-22 14:31:42.817699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7992f1ab9a'
down_revision = '20260521_v3_add_bed_profile_name'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_action'))
        batch_op.drop_index(batch_op.f('idx_audit_actor_id'))
        batch_op.drop_index(batch_op.f('idx_audit_created_at'))

    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admitted_children_rural', sa.Integer(), nullable=True))

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_record_date_dept'))
        batch_op.drop_index(batch_op.f('idx_record_date_of_admission'))
        batch_op.drop_index(batch_op.f('idx_record_date_status'))
        batch_op.drop_index(batch_op.f('idx_record_department_id'))
        batch_op.drop_index(batch_op.f('idx_record_history'))
        batch_op.create_index(batch_op.f('ix_records_date_of_admission'), ['date_of_admission'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_records_department_id'), type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_records_department_id'), 'departments', ['department_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_records_date_of_admission'))
        batch_op.create_index(batch_op.f('idx_record_history'), ['history'], unique=False)
        batch_op.create_index(batch_op.f('idx_record_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_record_date_status'), ['date_of_discharge', 'discharge_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_record_date_of_admission'), ['date_of_admission'], unique=False)
        batch_op.create_index(batch_op.f('idx_record_date_dept'), ['date_of_discharge', 'discharge_department'], unique=False)

    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('admitted_children_rural')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_action'), ['action'], unique=False)

    # ### end Alembic commands ###
