"""Add ambulatory records table

Revision ID: e30793237851
Revises: 20260330_add_department_fk
Create Date: 2026-05-29 22:40:04.765719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30793237851'
down_revision = '20260330_add_department_fk'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulatory_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_number', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('doctor', sa.String(length=200), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('discharge_status', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambulatory_records', schema=None) as batch_op:
        batch_op.create_index('idx_amb_date', ['date'], unique=False)
        batch_op.create_index('idx_amb_discharge_status', ['discharge_status'], unique=False)
        batch_op.create_index('idx_amb_doctor', ['doctor'], unique=False)
        batch_op.create_index('idx_amb_full_name', ['full_name'], unique=False)
        batch_op.create_index('idx_amb_updated_at', ['updated_at'], unique=False)

    op.drop_table('print_settings')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_daily_report_date'))

    op.drop_table('daily_reports')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('row_no')
        batch_op.drop_column('bed_capacity')
        batch_op.drop_column('bed_profile_name')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_date_of_admission'))
        batch_op.drop_column('date_of_admission')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_admission', sa.DATE(), nullable=True))
        batch_op.create_index(batch_op.f('ix_records_date_of_admission'), ['date_of_admission'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bed_profile_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('bed_capacity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('row_no', sa.INTEGER(), nullable=True))

    op.create_table('daily_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_date', sa.DATE(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('beds_total', sa.INTEGER(), nullable=True),
    sa.Column('beds_renovation', sa.INTEGER(), nullable=True),
    sa.Column('patients_start', sa.INTEGER(), nullable=True),
    sa.Column('admitted_total', sa.INTEGER(), nullable=True),
    sa.Column('admitted_rural', sa.INTEGER(), nullable=True),
    sa.Column('admitted_children', sa.INTEGER(), nullable=True),
    sa.Column('transferred_in', sa.INTEGER(), nullable=True),
    sa.Column('transferred_out', sa.INTEGER(), nullable=True),
    sa.Column('discharged_total', sa.INTEGER(), nullable=True),
    sa.Column('discharged_to_other', sa.INTEGER(), nullable=True),
    sa.Column('deaths', sa.INTEGER(), nullable=True),
    sa.Column('patients_end', sa.INTEGER(), nullable=True),
    sa.Column('patients_end_rural', sa.INTEGER(), nullable=True),
    sa.Column('mothers_with_children', sa.INTEGER(), nullable=True),
    sa.Column('free_male', sa.INTEGER(), nullable=True),
    sa.Column('free_female', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('admitted_children_rural', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'department_id', name=op.f('uq_daily_report_date_dept'))
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_daily_report_date'), ['report_date'], unique=False)

    op.create_table('print_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ministry', sa.VARCHAR(length=200), nullable=False),
    sa.Column('org_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('org_short_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('org_address', sa.VARCHAR(length=300), nullable=False),
    sa.Column('signer1_title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('signer1_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('signer2_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('signer2_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('form007_title', sa.VARCHAR(length=200), server_default=sa.text("'ЛИСТОК ОБЛІКУ РУХУ ХВОРИХ'"), nullable=False),
    sa.Column('form007_subtitle', sa.VARCHAR(length=200), server_default=sa.text("'і ліжкового фонду стаціонару'"), nullable=False),
    sa.Column('form016_title', sa.VARCHAR(length=200), server_default=sa.text("'ЗВЕДЕНА ВІДОМІСТЬ ОБЛІКУ РУХУ ХВОРИХ'"), nullable=False),
    sa.Column('form016_subtitle', sa.VARCHAR(length=200), server_default=sa.text("'і ліжкового фонду стаціонару'"), nullable=False),
    sa.Column('form007_form_no', sa.VARCHAR(length=50), server_default=sa.text("'Форма № 007/о'"), nullable=False),
    sa.Column('form007_decree', sa.VARCHAR(length=200), server_default=sa.text("'Затверджено наказом МОЗ України від 29.05.2013 р. № 110'"), nullable=False),
    sa.Column('form016_form_no', sa.VARCHAR(length=50), server_default=sa.text("'Форма № 016/о'"), nullable=False),
    sa.Column('form016_decree', sa.VARCHAR(length=200), server_default=sa.text("'Затверджено наказом МОЗ України від 27.12.05 р. № 760'"), nullable=False),
    sa.Column('form007_dept_title', sa.VARCHAR(length=200), server_default=sa.text("'Рух хворих і ліжкового фонду'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambulatory_records', schema=None) as batch_op:
        batch_op.drop_index('idx_amb_updated_at')
        batch_op.drop_index('idx_amb_full_name')
        batch_op.drop_index('idx_amb_doctor')
        batch_op.drop_index('idx_amb_discharge_status')
        batch_op.drop_index('idx_amb_date')

    op.drop_table('ambulatory_records')
    # ### end Alembic commands ###
