"""Add ambulatory records table

Revision ID: e30793237851
Revises: 20260330_add_department_fk
Create Date: 2026-05-29 22:40:04.765719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30793237851'
down_revision = '20260330_add_department_fk'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulatory_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_number', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('doctor', sa.String(length=200), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('discharge_status', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambulatory_records', schema=None) as batch_op:
        batch_op.create_index('idx_amb_date', ['date'], unique=False)
        batch_op.create_index('idx_amb_discharge_status', ['discharge_status'], unique=False)
        batch_op.create_index('idx_amb_doctor', ['doctor'], unique=False)
        batch_op.create_index('idx_amb_full_name', ['full_name'], unique=False)
        batch_op.create_index('idx_amb_updated_at', ['updated_at'], unique=False)
    # ### end Alembic commands ###
    # NOTE: автозгенеровані drop'и Form 007 (print_settings/daily_reports/departments/records)
    # навмисно прибрані — ця гілка містить і Форму 007, і амбулаторку. Міграція лише додає таблицю.


def downgrade():
    with op.batch_alter_table('ambulatory_records', schema=None) as batch_op:
        batch_op.drop_index('idx_amb_updated_at')
        batch_op.drop_index('idx_amb_full_name')
        batch_op.drop_index('idx_amb_doctor')
        batch_op.drop_index('idx_amb_discharge_status')
        batch_op.drop_index('idx_amb_date')

    op.drop_table('ambulatory_records')
