"""Add NSZU Corrections table

Revision ID: e451abd846fe
Revises: 20260109_remove_status
Create Date: 2026-01-18 14:01:42.002385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e451abd846fe'
down_revision = '20260109_remove_status'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nszu_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nszu_record_id', sa.String(length=100), nullable=False),
    sa.Column('doctor', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('fakt_summ', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nszu_corrections', schema=None) as batch_op:
        batch_op.create_index('idx_nszu_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_nszu_date', ['date'], unique=False)
        batch_op.create_index('idx_nszu_doctor', ['doctor'], unique=False)
        batch_op.create_index('idx_nszu_record_id', ['nszu_record_id'], unique=False)
        batch_op.create_index('idx_nszu_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_nszu_corrections_nszu_record_id'), ['nszu_record_id'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_departments_name'))
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_records_updated_by_users', 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_records_updated_by_users', type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.create_index(batch_op.f('idx_departments_name'), ['name'], unique=False)

    with op.batch_alter_table('nszu_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nszu_corrections_nszu_record_id'))
        batch_op.drop_index('idx_nszu_status')
        batch_op.drop_index('idx_nszu_record_id')
        batch_op.drop_index('idx_nszu_doctor')
        batch_op.drop_index('idx_nszu_date')
        batch_op.drop_index('idx_nszu_created_at')

    op.drop_table('nszu_corrections')
    # ### end Alembic commands ###
